In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
ma = [[0.343, 0.351, 0.306],
      [0.145, 0.368, 0.487]]

In [10]:
a = np.array(ma)

In [11]:
a.shape

(2, 3)

In [22]:
a.flatten()

array([ 0.343,  0.351,  0.306,  0.145,  0.368,  0.487])

In [12]:
a.flatten(order='F')

array([ 0.343,  0.145,  0.351,  0.368,  0.306,  0.487])

In [13]:
a.reshape(a.size, order='F')

array([ 0.343,  0.145,  0.351,  0.368,  0.306,  0.487])

In [15]:
[y  for x in [[row[i] for row in ma] for i in range(len(ma[0]))] for y in x]

[0.343, 0.145, 0.351, 0.368, 0.306, 0.487]

In [16]:
np.ravel(a.T)

array([ 0.343,  0.145,  0.351,  0.368,  0.306,  0.487])

In [20]:
a.T.ravel('F')

array([ 0.343,  0.351,  0.306,  0.145,  0.368,  0.487])

In [17]:
a

array([[ 0.343,  0.351,  0.306],
       [ 0.145,  0.368,  0.487]])